<?php

namespace ContainerFAWluaq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApp_MenuBuilderService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'app.menu_builder' shared autowired service.
     *
     * @return \App\Menu\Builder
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Menu/Builder.php';

        return $container->privates['app.menu_builder'] = new \App\Menu\Builder(($container->services['knp_menu.factory'] ?? $container->load('getKnpMenu_FactoryService')), ($container->services['.container.private.security.authorization_checker'] ?? $container->get_Container_Private_Security_AuthorizationCheckerService()), ($container->services['.container.private.security.token_storage'] ?? $container->get_Container_Private_Security_TokenStorageService()), ($container->services['doctrine'] ?? $container->getDoctrineService()));
    }
}
