<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEDy18LM\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEDy18LM/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerEDy18LM.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerEDy18LM\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerEDy18LM\App_KernelDevDebugContainer([
    'container.build_hash' => 'EDy18LM',
    'container.build_id' => '921bb3ba',
    'container.build_time' => 1660890179,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerEDy18LM');
